version: '3.1'
services:

  postgres:
    restart: always
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: iehr_test
      POSTGRES_PASSWORD: iehrt123!
      POSTGRES_DB: iehr_test
    ports:
      - "5432:5432"

      # persist data even if container shuts down volumes:
    volumes:
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  dyndoc-configurator-ui-backend:
    container_name: dyndoc-configurator-ui-backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    ports:
      - "8080:8080"
      - "10005:8000"
    depends_on:
      - postgres