server:
  port : 8081

spring:
  datasource:
    initialization-mode: never #for initial database population set to 'always'
    platform: postgres
    username: iehr
    password: 1234
    url: jdbc:postgresql://localhost:5432/iehr?currentSchema=iehr&useSSL=false
    sqlScriptEncoding: UTF-8
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.type.desctiptor.sql: trace


