########################################################################################################################
#                                                                                                                      #
#                                                                                                                      #
########################################################################################################################

server:
  port: 8081
  servlet:
    context-path: /dyndoc-configurator-ui-backend
  tomcat:
    mbeanregistry:
      enabled: true
    accesslog:
      enabled: true
      pattern: '{"threadName":"%I", "remoteIP": "%a", "localIP": "%A", "clientHost": "%h", "protocol": "%H", "requestMethod": "%m", "requestURL": "%r", "statusCode": "%s", "elapsedTime": "%D", "responseTime": "%F", "date": "%t", "user": "%u", "requestURI": "%U", "server": "%v", "spanID": "%{X-B3-spanid}i", "traceID": "%{X-B3-traceid}i", "parentSpanID": "%{X-B3-ParentSpanId}i"}'
      prefix: access-log
      suffix: .log
      max-days: 5
      rename-on-rotate: true
  # Enable graceful shutdown
  shutdown: graceful

logging:
  level:
    hr.ericsson.ehealth.belarus: DEBUG
    org.springframework.security: DEBUG
  payload: true
  error:
    stacktrace: true
  spring:
    boot:
      application: hr.ericsson.ehealth.belarus.dyndoc.configurator.Application
  kafka:
    topic: by-application-topic
    bootstrap:
      servers: messaging-broker-o1:9092,messaging-broker-o2:9092,messaging-broker-o3:9092

spring:
  datasource:
    initialization-mode: never #for initial database population set to 'always'
    platform: postgres
    username: iehr_test
    password: iehrt123!
    url: jdbc:postgresql://app-db-princ-o1.dc1.lab.by.etk.hr:5444/iehr_test?currentSchema=iehr_test&useSSL=false
    sqlScriptEncoding: UTF-8
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak-o1.dc1.lab.by.etk.hr:8080/auth/realms/lab/protocol/openid-connect/certs

  liquibase:
    enabled: true
    drop-first: true
    change-log: classpath:/db.changelog/db.changelog-master.yaml
    default-schema: iehr
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  banner:
    location: classpath:/banner-dev.txt
  session:
    store-type: none
  lifecycle:
    timeout-per-shutdown-phase: 20s

# actuator
management:
  endpoint:
    health:
      probes:
        enabled: true
  #  endpoint.health.show-details: always
  health.defaults.enabled: false
  endpoints.web.exposure.include: refresh,health,info,metrics,prometheus


## Configuring actuator/info endpoint
info:
  app:
    name: dyndoc-configurator-ui-backend
    description: DYNDOC configurator eHealth Microservice
    version: 0.0.1


swagger:
  title: dyndoc-configurator-ui-backend
  description: DYNDOC configurator eHealth Microservice
  version: 0.0.1
  termsOfServiceUrl: \#
  contactName: Dzmitry Harlach
  contactUrl: \#
  contactEmail: dzmitry.harlach@ericsson.com
  license: License of API
  licenseUrl: \#

by:
  errors:
    languages:
      - en
      - ru

auth-lib:
  tokenLifetimeMinutes: 1440 # 24 hours
  ignored-patterns:
    - /static/**
    - /actuator/**
    - /v2/api-docs/**
    - /v2/api-docs
    - /swagger-resources/**
    - /swagger-ui.html**
    - /swagger-ui/
    - /swagger-ui/**
    - /webjars/**
    - favicon.ico
    - /api/oid/generate
    - /api/oid/validate
    - /api/oid/external-id
