spring:
  datasource:
    initialization-mode: always #for initial database population set to 'always'
    platform: postgres
    username: iehr_test
    password: iehrt123!
    url: jdbc:postgresql://postgres:5432/iehr_test?currentSchema=iehr_test&useSSL=false
    sqlScriptEncoding: UTF-8
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
#         specify port 8081 if you are running keylock-mock-service in a docker container or 8080 locally
          jwk-set-uri: http://localhost:8081/certs

# FHIR client configuration
fhir:
  default:
    serverAddress: http://localhost:8070/fhir
  serverAddress: http://localhost:8070/fhir
  connectTimeout: 200000
  socketTimeout: 200000
  poolMaxTotal: 100
  poolMaxPerRoute: 100

auth-lib:
  claims:
    id: sub
    username: preferred_username
    firstName: given_name
    lastName: family_name
    fullName: name
    practitionerOid: practitioner_oid
    issuer: iss
    authorities: authorities
  token-lifetime-minutes: 1440 # 24 hours
  claim-names: realm_access,resource_access
  oid-delimiter: .
  validation: true
  cache-department: false
  header-department: false
  header-department-name: CurrentDepartment
  ignored-patterns:
    - /static/**
    - /actuator/**
    - /v2/api-docs/**
    - /v2/api-docs
    - /swagger-resources/**
    - /swagger-ui.html**
    - /swagger-ui/
    - /swagger-ui/**
    - /webjars/**
    - favicon.ico
    - /icd-api/**
    - /icd-api/
    - /icd-api
    - /cts/**
    - /cts/
    - /cts
    - /referral/**
    - /referral/
    - /referral
  auth-patterns:
    - /api/**